two-clock/backend

src/main/java/com/twoclock/gitconnect/domain/board/entity/Board.java, src/main/java/com/twoclock/gitconnect/domain/board/entity/BoardFile.java, src/main/java/com/twoclock/gitconnect/domain/comment/entity/Comment.java, src/main/java/com/twoclock/gitconnect/domain/page/entity/PageViewHistory.java
* #12 
* board , boardFile, Comment, pageViewHistory Entity 연관관계 설정
@openmpy 님 불철주야 노고가 많으십니다~
기반 잡아주신 도메인 기반으로 게시판 관련하여 엔티티 관계 설정 완료하였습니다.
JPA에는 아직 익숙하지가 않아서 관계 설정이 좀 많이 서투른 점 양해 부탁드립니다.
`@ManyToOne` 관계에 대해서 N+1 이슈가 발생할 수 있어 지연로딩으로 설정하였습니다.
추후 이슈가 될 사항에 대해서 피드백 부탁드리겠습니다~
감사합니다 !
=> feat: Setting up bulletin board-related entity relationships

src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardReqeustDto.java, src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardResponseDto.java, src/main/java/com/twoclock/gitconnect/domain/board/entity/Board.java, src/main/java/com/twoclock/gitconnect/domain/board/entity/constants/Category.java, src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java, src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java, src/main/java/com/twoclock/gitconnect/domain/comment/entity/Comment.java, src/main/java/com/twoclock/gitconnect/global/dummy/DummyDevlnit.java, src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java, src/main/java/com/twoclock/gitconnect/global/model/HttpResponse.java, src/main/java/com/twoclock/gitconnect/global/model/RestResponse.java
* #16 
* 프로젝트 Init 시점에서 Dummy User Data 등록 - 테스트 용도
* 게시판 등록 API 생성
* HttpResponse 공통 응답 객체 생성
---
> 게시판 등록 API 
**요청 주소 :  /api/v1/boards (post)**
> request
```
{
"title" : "제목",
"content" : "대충 내용",
"category" : "BD1"
}
```
> response
```
{
"httpStatus": 200,
"data": null
}
```
=> feat: 게시판 등록 API 생성

src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java, src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java
* #17 
* 본인의 게시판 삭제 API(Soft Delete)
---
> 게시판 삭제 API
> 요청 주소 : /api/v1/boards/{boardKey} (delete)
> response
```
{
"data": null
}
```
* Soft Delete 이후 isView 컬럼에 대한 값이 `FALSE` 로 변경 확인
=> feat: Add Delete Board API

build.gradle, src/main/java/com/twoclock/gitconnect/domain/member/service/MemberAuthService.java, src/main/java/com/twoclock/gitconnect/domain/member/web/MemberAuthController.java, src/main/java/com/twoclock/gitconnect/global/config/RedisConfig.java, src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java, src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java, src/main/java/com/twoclock/gitconnect/global/jwt/JwtService.java, src/main/java/com/twoclock/gitconnect/global/jwt/dto/JwtTokenInfoDto.java
* #25 
- 로그인 시 Refresh Token 이 발급됩니다. (일주일) 
- 발급된 Refresh Token 은 Redis 와 Cookie 에 저장됩니다.
- Redis 에는 ``Key: GitHub ID, Value: Refresh Token`` 으로 저장됩니다.
- ``/api/v1/members/auth/refresh`` 엔드포인트로 POST 요청을 보낼 시 새로운 JWT 토큰이 발급됩니다.
1. 정상적인 JWT 토큰인지 검증합니다.
2. 정상적인 JWT 토큰이라면 Cookie 에 저장된 Refresh Token 에서 GitHub ID 를 추출합니다.
3. 추출한 GitHub ID가 Redis 에 저장되어 있는지 확인합니다.
4. Redis 에 저장된 GitHub ID 라면 새로운 Access Token 과 Refresh Token 을 발급합니다.
- Redis 에 새로 발행된 Refresh Token 으로 값이 갱신 되기 때문에 기존 Refresh Token 은 사용할 수 없게 됩니다. (3번에 걸리게 됨)
```yml
spring:
data:
redis:
port: 6379
host: localhost
```
@jjangsky 님~ 여름이 얼른 끝났으면 좋겠네요.. 🥵
로그인 관련해서 Refresh Token 발급과 재발급 기능을 추가했습니다.
확인 부탁드리겠습니다 ~
=> feat: Add Redis Integration and JWT Token Refresh Functionality

build.gradle, src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardRequestDto.java, src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardResponseDto.java, src/main/java/com/twoclock/gitconnect/domain/board/dto/SearchRequestDto.java, src/main/java/com/twoclock/gitconnect/domain/board/dto/SearchResponseDto.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardRepository.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardRepositoryImpl.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/CustomBoardRepository.java, src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java, src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java, src/main/java/com/twoclock/gitconnect/domain/member/dto/MemberInfoDto.java, src/main/java/com/twoclock/gitconnect/global/dummy/DummyDevlnit.java
* #14 
> 계정 홍보, 저장소 홍보, 신고 게시판 조회 API 생성
주소 : `/api/v1/boards`
**RequestParam**
- word(검색 입력값)
- type(검색 조건)
- category(게시판 종류, 필수값)
- page(현재 페이지, Defualt = 1)
- size(한번에 조회할 수량, Default =10)
> ex: 제목중에 '테스트' 라는 단어가 포함된 계정 홍보 게시글
> http://localhost:8082/api/v1/boards?searchWord=테스트&searchType=title&category=BD1
**Response**
```
{
"data": {
"totalPages": 1,
"totalElements": 10,
"size": 10,
"content": [
{
"id": 9,
"title": "계정 홍보 테스트 게시글8",
"content": "테스트 게시글 내용8",
"nickname": "테스트 유저",
"category": "BD1",
"member": {
"createdDateTime": "2024-08-11T20:47:43.543585",
"modifiedDateTime": null,
"id": 1,
"login": "loginId",
"avatarUrl": "/uploads/profile/test.jpg",
"name": "테스트 유저",
"role": "ROLE_USER"
}
},
{
"id": 10,
"title": "계정 홍보 테스트 게시글9",
"content": "테스트 게시글 내용9", …
```
=> feat: Creating a bulletin board API using Querydsl

src/main/java/com/twoclock/gitconnect/global/exception/GlobalExceptionHandler.java, src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java
* #21 
> 전역 예외처리 추가
-  `MethodArgumentTypeMismatchException`
-  `AccessDeniedException`
-  `MissingRequestCookieException`
-  `MethodArgumentNotValidException`
-> 해당 Exception 들은 Client 측 오류로 생각하여 `@SlackNotification`을 부여하지는 않았습니다.
> 게시판 등록 API 실행 시, 제목을 입력 안한 경우
잘못된 Request를 전송할 경우 설정한 Default Message가 발송되는 것 확인하였습니다.
=> feat: GolbalException add 4XX error 

src/main/java/com/twoclock/gitconnect/global/constants/GitHubUri.java, src/main/java/com/twoclock/gitconnect/openapi/github/dto/FollowRespDto.java, src/main/java/com/twoclock/gitconnect/openapi/github/service/GithubAPISerivce.java, src/main/java/com/twoclock/gitconnect/openapi/github/service/GithubAPIService.java, src/main/java/com/twoclock/gitconnect/openapi/github/web/GithubAPIController.java
* #38 
> 실제 Github Following/Follower List 요청 시 반환되는 Response
```
{
"login": "youchanKim",
"id": 132042138,
"node_id": "U_kgDOB97Nmg",
"avatar_url": "https://avatars.githubusercontent.com/u/132042138?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/youchanKim",
"html_url": "https://github.com/youchanKim",
"followers_url": "https://api.github.com/users/youchanKim/followers",
"following_url": "https://api.github.com/users/youchanKim/following{/other_user}",
"gists_url": "https://api.github.com/users/youchanKim/gists{/gist_id}",
"starred_url": "https://api.github.com/users/youchanKim/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/youchanKim/subscriptions",
"organizations_url": "https://api.github.com/users/youchanKim/orgs",
"repos_url": …
```
=> feat: add Github API following/follower list using accessToken

src/main/java/com/twoclock/gitconnect/domain/member/dto/MemberGitHubTokenDto.java, src/main/java/com/twoclock/gitconnect/domain/member/service/MemberAuthRedisService.java, src/main/java/com/twoclock/gitconnect/domain/member/service/MemberAuthService.java, src/main/java/com/twoclock/gitconnect/global/config/RedisConfig.java, src/main/java/com/twoclock/gitconnect/global/constants/GitHubUri.java, src/main/java/com/twoclock/gitconnect/global/util/RestClientUtil.java
* #43 
- 로그인 시 GitHub Access Token 과 Refresh Token 이 Redis 에 저장됩니다.
- 키 ``"github-id:1234"``, 밸류 ``"MemberGitHubTokenDto"``
- /refresh 엔드포인트 호출 시 새로운 GitHub Access Token 과 Refresh Token 이 발급됩니다.
- 기존에 발급된 토큰들은 사용할 수 없게 됩니다.
- /logout 엔드포인트 호출 시 발급된 GitHub Acess Token 과 Refresh Token 을 사용할 수 없게 됩니다.
=> feat: Implement GitHub token refresh and persistence

src/main/java/com/twoclock/gitconnect/domain/like/entity/Like.java, src/main/java/com/twoclock/gitconnect/domain/like/entity/Likes.java, src/main/java/com/twoclock/gitconnect/domain/like/repository/LikeRepository.java, src/main/java/com/twoclock/gitconnect/domain/like/service/LikeService.java, src/main/java/com/twoclock/gitconnect/domain/like/web/LikeController.java, src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java
* #46 
**게시글에 대해서 좋아요를 등록할 수 있음**
- 이미 좋아요를 누른 게시글에 대해서는 좋아요를 추가할 수 없음
- 게시글이 삭제되지 않은 상태이며 사용자도 존재해야함
> API : `/api/v1/like/{boardId}`   [Post]
**좋아요 눌렀던 게시글에 대해서 좋아요 취소할 수 있음**
- 자신이 좋아요를 눌렀던 게시글에 대해서만 삭제 처리를 할 수 있음
> API : `/api/v1/like/{boardId}`   [Delete]
(DB에서 값 자체를 삭제하는 Delete 처리)
=> feat: add Board like API

src/main/java/com/twoclock/gitconnect/domain/like/dto/LikesRespDto.java, src/main/java/com/twoclock/gitconnect/domain/like/repository/LikeRepository.java, src/main/java/com/twoclock/gitconnect/domain/like/service/LikeService.java, src/main/java/com/twoclock/gitconnect/domain/like/web/LikeController.java
* #52 
게시글의 ID를 사용하여 좋아요 목록을 확인할 수 있는 API 추가
> API : `/api/v1/likes/{boardId}` (Get)
**Response**
```
{
"data": [
{
"id": 1,
"login": "jjangsky",
"avatarUrl": "https://avatars.githubusercontent.com/u/103441154?v=4",
"name": "짱스키",
"gitHubId": "103441154",
"createdDateTime": "2024-08-20T23:15:18.067118"
}
]
}
```
만약 게시글의 좋아요가 없는 경우는 따로 Exception 처리를 하지 않고 빈 배열을 반환시킵니다.
```
{
"data": []
}
```
=> feat: Add API to check Likes of board

.gitignore, build.gradle, compose.yml, src/main/java/com/twoclock/gitconnect/domain/chat/dto/ChatMessageSaveReqDto.java, src/main/java/com/twoclock/gitconnect/domain/chat/dto/ChatMessageSaveRespDto.java, src/main/java/com/twoclock/gitconnect/domain/chat/entity/ChatMessage.java, src/main/java/com/twoclock/gitconnect/domain/chat/entity/ChatRoom.java, src/main/java/com/twoclock/gitconnect/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/twoclock/gitconnect/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatMessageService.java, src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatRoomService.java, src/main/java/com/twoclock/gitconnect/domain/chat/web/ChatMessageController.java, src/main/java/com/twoclock/gitconnect/domain/chat/web/ChatRoomController.java, src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java, src/main/java/com/twoclock/gitconnect/global/config/WebSocketConfig.java, src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java, src/main/java/com/twoclock/gitconnect/global/security/WebSocketPreHandler.java
* #58, #59 
- 1대1 채팅 생성 기능을 추가 했습니다.
- `POST /api/v1/chatrooms?receiveId={receiveGitHubId}`
- 채팅방 고유 ID를 따로 설정해줬습니다. (채팅 만든 회원의 GitHub ID - 채팅 대상 회원의 GitHub ID)
- 채팅방 중복 생성을 방지했습니다.
- 채팅 시 메세지 내용 저장은 NoSQL DB 인 MongoDB 를 이용했습니다.
- 다양한 형태의 정보를 유연하게 저장하고 빠르게 처리할 수 있습니다.
- 데이터가 많아져도 쉽게 확장할 수 있고, 실시간 처리가 잘 됩니다.
- 1대1 채팅 삭제 기능을 추가했습니다.
- `DELETE /api/v1/chatrooms/{chatRoomId}`
- Soft Delete 를 적용했습니다.
- Docker Compose 에 MongoDB 를 추가했습니다.
- application.yml 에 MongoDB 관련된 내용이 추가됐습니다.
```yml
spring:
data:
mongodb:
uri: mongodb://root:1234@localhost:27017/chat
```
```sql
use chat;
db.createCollection("messages");
db.createUser({
user: "root",
pwd: "1234",
roles: [{role: "readWrite", db: "chat"}]
});
db.grantRolesToUser("root", [{role: "readWrite", db: "chat"}]);
```
=> feat: Add WebSocket Support and MongoDB Integration for Chat Room Management

src/main/java/com/twoclock/gitconnect/domain/chat/dto/ChatMessageRespDto.java, src/main/java/com/twoclock/gitconnect/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatRoomService.java, src/main/java/com/twoclock/gitconnect/domain/chat/web/ChatRoomController.java
* #60
- 채팅방에 보낸 메세지들을 확인할 수 있습니다.
- `GET /api/v1/chatrooms/{chatRoomId}/messages?page=0&size=10` (size 는 필수 항목이 아닙니다)
- 페이지네이션을 적용시켰습니다.
- 보낸일자 기준으로 내림차순 정렬을 시켰습니다.
- 채팅방에 참여 인원이 아닐 시 `CH-003` 에러가 나타납니다.
```json
{
"code": "CH-003",
"message": "접근할 수 없는 채팅방입니다.",
"errors": null
}
```
```json
{
"data": [
{
"login": "openmpy",
"message": "에잉",
"createdDateTime": "2024-08-22T02:11:05.859"
},
{
"login": "openmpy",
"message": "이잉",
"createdDateTime": "2024-08-22T02:11:05.221"
},
{
"login": "openmpy",
"message": "이잉",
"createdDateTime": "2024-08-22T02:11:04.529"
},
{
"login": "openmpy",
"message": "이이이이",
"createdDateTime": "2024-08-22T02:11:03.844"
},
{
"login": "openmpy",
"message": "이잉",
"createdDateTime": "2024-08-22T02:11:03.06"
},
{
"login": "openmpy",
"message": "아에이", …
```
=> feat: Add pagination for chat messages endpoint

build.gradle, src/main/java/com/twoclock/gitconnect/domain/comment/dto/CommentRegReqDto.java, src/main/java/com/twoclock/gitconnect/domain/comment/dto/CommentRegistReqDto.java, src/main/java/com/twoclock/gitconnect/domain/comment/entity/Comment.java, src/main/java/com/twoclock/gitconnect/domain/comment/service/CommentService.java, src/main/java/com/twoclock/gitconnect/domain/comment/web/CommentController.java, src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java
* #53 
게시글에 대해서 댓글을 추가할 수 있는 API 도입하였습니다.
> API : `api/v1/comments`
**Request**
```
{
"boardId" : 1,
"content" : "테스트 내용입니다."
}
```
-> `content` 필드에 비속어가 포함될 경우 필터링 되어 사용자에게 반환 처리 됩니다.
```
{
"code": "W-001",
"message": "금지어가 포함되어 있습니다.",
"errors": null
}
```
[비속어 관련 라이브러리](https://github.com/VaneProject/bad-word-filtering)
=> faet:  Add commenting and profanity filtering to boards

src/main/java/com/twoclock/gitconnect/domain/chat/dto/ChatRoomRespDto.java, src/main/java/com/twoclock/gitconnect/domain/chat/repository/ChatMessageRepository.java, src/main/java/com/twoclock/gitconnect/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/twoclock/gitconnect/domain/chat/repository/ChatRoomRepositoryImpl.java, src/main/java/com/twoclock/gitconnect/domain/chat/repository/CustomChatRoomRepository.java, src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatRoomService.java, src/main/java/com/twoclock/gitconnect/domain/chat/web/ChatRoomController.java, src/main/java/com/twoclock/gitconnect/global/dummy/DummyDevlnit.java, src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java
* #60 
- 더미 데이터에 멤버 부분을 리스트 형식으로 변경 했습니다.
- 채팅방 목록 기능을 추가했습니다.
- `GET /api/v1/chatrooms`
- 조회 시 `상대방 아이디, 프로필 URL, 마지막 대화, 마지막 대화 생성 일자`를 내려줬습니다.
- Querydsl 을 이용해서 `ID 기준으로 중복되는 채팅방`을 필터링 해줬습니다.
- 채팅 메세지의 `createdDateTime` 기준으로 내림차순 정렬을 했습니다.
- polling 방식을 생각하고 구현 했습니다.
- 추후 프론트가 완성 된다면 소켓 방식으로 변경할 예정입니다.
```json
{
"data": [
{
"login": "loginId-2",
"avatarUrl": "/uploads/profile/test2.jpg",
"lastMessage": "하하",
"createdDateTime": "2024-08-23T17:00:37.016"
},
{
"login": "loginId-1",
"avatarUrl": "/uploads/profile/test1.jpg",
"lastMessage": "안녕하세요",
"createdDateTime": "2024-08-23T17:00:25.243"
}
]
}
```
=> feat: Add ChatRoomRepository query, and getChatRooms endpoint

src/main/java/com/twoclock/gitconnect/domain/comment/service/CommentService.java, src/main/java/com/twoclock/gitconnect/domain/comment/web/CommentController.java
* #55 
등록한 댓글에 대해서 삭제할 수 있는 기능 추가
-> 데이터의 완전한 삭제가 아닌 조회 여부 컬럼 update(soft delete)
> API : `/api/v1/comments/{commentId} [Put 요청]
* IS_VIEW 컬럼에 대해서 UPDATE 확인
=> feat: add delete comment API

src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardRequestDto.java, src/main/java/com/twoclock/gitconnect/domain/board/dto/SearchResponseDto.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardRepositoryImpl.java, src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java, src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java, src/main/java/com/twoclock/gitconnect/global/dummy/DummyDevlnit.java
* #65 
* 게시판 Business Layer 검증 로직 Method로 분리(사용자 및 게시글)
* 댓글 더미 데이터 생성(5건)
* 게시글 작성 및 수정 시 비속어 필터링 적용
* 게시글 검색 시 댓글 수, 좋아요 수 함께 조회
> ![image](https://github.com/user-attachments/assets/cf63decc-7046-4535-9c48-e3eae3baa1f9)
=> refactor: boards API refactor and get data with comment and likes

src/main/java/com/twoclock/gitconnect/domain/comment/dto/CommentListRespDto.java, src/main/java/com/twoclock/gitconnect/domain/comment/repository/CommentRepository.java, src/main/java/com/twoclock/gitconnect/domain/comment/service/CommentService.java, src/main/java/com/twoclock/gitconnect/domain/comment/web/CommentController.java
* #56 
* 게시글의 대해서 댓글을 조회할 수 있는 API 추가
> API : `/api/v1/boards/{boardId}/comments`
**Response**
```
{
"data": [
{
"id": 1,
"memberId": 3,
"avatarUrl": "https://avatars.githubusercontent.com/u/103441154?v=4",
"nickname": "짱스키",
"content": "댓글 1",
"modifiedDateTime": null,
"createdDateTime": "2024-08-25T23:19:23.389284"
},
{
"id": 2,
"memberId": 3,
"avatarUrl": "https://avatars.githubusercontent.com/u/103441154?v=4",
"nickname": "짱스키",
"content": "댓글 2",
"modifiedDateTime": null,
"createdDateTime": "2024-08-25T23:19:28.074806"
},
{
"id": 3,
"memberId": 3,
"avatarUrl": "https://avatars.githubusercontent.com/u/103441154?v=4",
"nickname": "짱스키",
"content": "이게 가장 최신 댓글",
"modifiedDateTime": null,
"createdDateTime": "2024-08-25T23:19:33.430515"
}
]
}
```
=> feat: add API to view comments on boards

.gitignore, build.gradle, compose.yml, prometheus/prometheus.yml, src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java
* #63 
- 액츄에이터 & 프로메테우스 & 그라파나 연동 작업을 진행 했습니다.
- 액츄에이터: `http://localhost:8090/actuator`
- 프로메테우스: `http://localhost:9090`
- 그라파나: `http://localhost:3000`
- 아이디: `admin`, 비밀번호: `admin`
- 개발 단계이기 때문에 모든 계정이 접근 가능하도록 설정 했습니다.
- 추후에 어드민 계정만 접근 가능하도록 설정 할 예정입니다.
- 서비스가 얼추 완성 된다면 메트릭을 수집해서 좀 더 디테일하게 모니터링 작업을 진행할 예정입니다. 
1. `http://localhost:3000` 접속 하시면 로그인 하라는 화면이 뜹니다.
2. 아이디: `admin`, 비밀번호: `admin` 을 적고 로그인을 해줍니다.
3. `Update your password` 창이 뜬다면 입력폼 왼쪽 하단에 `Skip` 을 눌러줍니다.
4. 왼쪽 상단에 `메뉴 > Connections > Data sources` 버튼을 눌러줍니다.
5. 화면 중앙에 `Add data source` 버튼을 눌러줍니다.
6. `Prometeus` 를 선택해줍니다.
7. `Connection` 입력창에 `http://prometheus:9090` 을 입력해주고 쭉 내려서 `Save & test` 버튼을 눌러줍니다.
8. 정상적으로 연결이 됐다면 `메뉴 > Dashboards` 버튼을 눌러줍니다.
9. 오른쪽 상단에 `New` 버튼을 누르고 `Import` 를 선택합니다.
10. `URL or ID` 입력창에 `4701` 또는 …
=> feat: Add Monitoring with Prometheus and Grafana

src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardCacheDto.java, src/main/java/com/twoclock/gitconnect/domain/board/dto/SearchRequestDto.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardCacheRepository.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardRepositoryImpl.java, src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java, src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java, src/main/java/com/twoclock/gitconnect/domain/member/entity/constants/Role.java, src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java, src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java
* #72 
> **도배성 게시글을 방지하기 위한 게시글 작성 후 5분 뒤 추가 작성 가능 로직 추가**
연속 작성 시, 해당 Exception 반환 처리
```
{
"code": "B-004",
"message": "게시글은 5분에 1번 작성할 수 있습니다.",
"errors": null
}
```
-> 각 카테고리 별로 제한을 두었으며 계정 홍보 게시판(BD1) 작성 후 저장소 홍보 게시판(BD2) 게시글 연속 작성 가능
> **신고 게시판 로직 추가**
- 신고 게시글은 본인이 신고한 게시글만 조회할 수 있음
- 관리자는 모든 신고 게시글을 조회할 수 있다.
**유저 권한으로 조회**
-> 본인이 작성한 게시글만 조회됨
**권한으로 조회**
-> 전체 신고 게시글 조회 가능
=> feat: Report  board viewing rights and boards creation delay

src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardRequestDto.java, src/main/java/com/twoclock/gitconnect/domain/board/entity/Board.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardFileRepository.java, src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java, src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java, src/main/java/com/twoclock/gitconnect/global/s3/S3Service.java
* #79 
* #80
> **게시글 수정 시, 파일 변경 확인 후 삭제처리**
이미 게시글의 등록된 3개의 사진 중 뒷 자리가 `..a27b.png` 파일을 제외하고 삭제 후 새로운 파일 을 등록한 경우
수정 과정에서 파일 2개 삭제 후 파일 1개 새로 등록 완료 
S3에서도 파일 삭제 완료하였습니다.
> **게시글 삭제 시, 파일 일괄 삭제**
`/api/v1/boards/{boardId}` [Delete] 로 동일하게 요청 시 해당 게시글이 갖고 있는 모든 Image File 일괄 삭제 처리
- DB 파일 정보 삭제
- S3 파일 삭제
=> feat: Image file deletion processing when editing or deleting a boards

src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardDetailRespDto.java, src/main/java/com/twoclock/gitconnect/domain/board/entity/Board.java, src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java, src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java, src/main/java/com/twoclock/gitconnect/domain/comment/dto/CommentListRespDto.java, src/main/java/com/twoclock/gitconnect/domain/comment/repository/CommentRepository.java, src/main/java/com/twoclock/gitconnect/domain/like/dto/LikesRespDto.java, src/main/java/com/twoclock/gitconnect/domain/like/repository/LikeRepository.java, src/main/java/com/twoclock/gitconnect/domain/member/dto/MemberLoginRespDto.java, src/main/java/com/twoclock/gitconnect/domain/member/service/MemberService.java, src/main/java/com/twoclock/gitconnect/global/config/RedisConfig.java, src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java
* #84 
> **게시판 상세조회 API 추가**
API : `/api/v1/boards/{boardId}`   [GET]
**Response**
```
{
"data": {
"id": 5,
"title": "계정 홍보 테스트 게시글4",
"content": "테스트 게시글 내용4",
"nickname": "테스트 유저 1",
"category": "BD1",
"member": {
"login": "loginId-1",
"gitHubId": "1234",
"avatarUrl": "/uploads/profile/test1.jpg",
"name": "테스트 유저 1"
}
}
}
```
- 게시판 상세보기 또한 전체 조회와 동일하게 신고 게시판의 경우 로그인 필요하며 본인의 게시물만 확인할 수 있습니다.
- 관리자 계정의 경우 모든 신고게시판 조회 가능
- 그 외 게시판은 전부 조회 가능(권한 필요X)
- 게시판 상세보기도 Redis를 사용하여 캐싱처리를 하였습니다.
- 유저 조회에서 사용한 동일한 cacheManager 사용(ttl 10분 설정)
추가적으로 최초 상세 조회 API 설계할 때 게시글의 정보와 좋아요 수, 댓글 수, 좋아요 목록(10명), 댓글 목록(10개)를
전부 반환하려고 하였으나, 좋아요 정보와 댓글 정보는 변경점이 많아 캐싱 처리를 하는데 있어서 효율이 떨어질거라 생각하여
최종적으로 게시글의 정보만 반환하였습니다.
현재 좋아요 목록 조회 및 댓글 목록 조회가 페이징처리가 되어 있지 않아서 추후 이슈 등록 후 다시 작업하겠습니다.
=> feat: add board details view API addition and caching processing

src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardWithCategoryRespDto.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardFileRepository.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardRepository.java, src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java, src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java, src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java, src/main/java/com/twoclock/gitconnect/global/dummy/DummyDevlnit.java
* #90 
* 무한 스크롤 구현을 위해서 전체 게시글 불러오는 방식을 수정했습니다.
* 기존에 만들어 두셨던 getBoardList 기능은 검색 기능으로 수정해서 적용하면 될거 같습니다.
=> feat: Create endpoint for fetching boards by category

build.gradle, src/test/java/com/twoclock/gitconnect/data/DummyDataTest.java
* #98 
* 100명의 회원과 1000만건 게시글 데이터를 넣을 수 있는 기능입니다.
* faker 라이브러리와 jdbc bulk insert 를 사용해서 구현 했습니다.
* 추후에 성능 개선 작업을 할 때 이용하시면 될거 같습니다.
1000만건 기준으로 8분정도 걸립니다.
=> test: Add dummy data test with Faker library

src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardDetailRespDto.java, src/main/java/com/twoclock/gitconnect/domain/board/dto/BoardFileRespDto.java, src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java
* #96 
게시글 상세조회 API 요청 시 게시글 등록일 및 사진 이미지 정보 출력
**Response**
```
{
"data": {
"id": 301,
"title": "사진 등록 테스트",
"content": "수정도 할꺼임 ㅋㅋ",
"nickname": "짱스키",
"category": "BD1",
"createdDateTime": "2024-09-11T00:24:29.360845",   /** 게시글 등록일 추가*/
"member": {
"login": "jjangsky",
"gitHubId": "103441154",
"avatarUrl": "https://avatars.githubusercontent.com/u/103441154?v=4",
"name": "짱스키"
},
"fileList": [  /** 파일 목록 추가 */
{
"id": 1,
"originalName": "스크린샷 2023-03-29 201201.png",
"fileUrl": "https://git-************.ap-nort************.amazonaws.com/fbeff8568d1************23bfb86.png"
},
{
"id": 2,
"originalName": "스크린샷 2023-03-29 201243.png",
"fileUrl": "https://git-************.ap-north************.amazonaws.com/22185b94526************70bdeb32d62f.png"
},
{
"id": 3, …
```
=> refactor: when get a boardDetailAPI, images are also viewed

src/main/java/com/twoclock/gitconnect/domain/board/entity/Board.java, src/main/java/com/twoclock/gitconnect/domain/board/repository/BoardRepository.java, src/main/java/com/twoclock/gitconnect/domain/board/service/BoardService.java, src/main/java/com/twoclock/gitconnect/domain/board/web/BoardController.java
* #104
> 기존의 상세보기 API 요청 시, 하나의 서비스로 상세보기 조회와 조회 수 증가 로직을 두가지 넣다보니
상세보기 데이터가 캐싱되는 경우 조회 수 증가 로직이 실행되지 않는 이슈가 있었습니다.
**상세보기 조회 / 조회 수 증가 서비스 로직 분리**
분리 결과 최초 API 요청 시에는 조회와 증가 SQL을 확인할 수 있으며
그 이후에는 조회 수 증가 SQL만 확인할 수 있습니다.
=> bug: Increased number of views when viewing detailed boards

src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatMessageService.java, src/main/java/com/twoclock/gitconnect/domain/comment/service/CommentService.java, src/main/java/com/twoclock/gitconnect/domain/like/service/LikeService.java, src/main/java/com/twoclock/gitconnect/domain/notification/dto/NotificationRespDto.java, src/main/java/com/twoclock/gitconnect/domain/notification/entity/Notification.java, src/main/java/com/twoclock/gitconnect/domain/notification/entity/constants/NotificationType.java, src/main/java/com/twoclock/gitconnect/domain/notification/repository/NotificationRepository.java, src/main/java/com/twoclock/gitconnect/domain/notification/service/NotificationService.java, src/main/java/com/twoclock/gitconnect/domain/notification/web/NotificationController.java, src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java, src/main/java/com/twoclock/gitconnect/global/exception/constants/ErrorCode.java
* #93 
> **알림 발송 API**
API : `/api/v1/notification` [GET]
* #97 에서 이미 추가한 기능이지만 수정사항 존재
(이전에는 알림이 존재하던 존재하지 않던 결과를 바로 반환)
해당 API를 실행하면 반환할 알림이 존재하지 않으면 60초동안 결과 반환이 지연됩니다.
- 60초 Timeout 이후에는 빈 배열 반환처리 됨
알람 API가 지연되는 도중 새로운 알람이 생기는 경우에는 바로 응답을 합니다.
- ex) 자신의 게시글에 새로운 댓글이 생기는 경우
---
> **알림 목록 확인 API**
API : `/api/v1/notification/list` [GET]
알림 발송일 기준으로 내림차순 처리
**Response**
```
{
"data": [
{
"id": 7,
"message": "jjangsky님이 댓글을 남겼습니다.",
"createdDateTime": "2024-09-18T23:04:40.959413",
"isRead": false
},
{
"id": 6,
"message": "jjangsky님이 댓글을 남겼습니다.",
"createdDateTime": "2024-09-18T23:02:45.177312",
"isRead": false
}
]
}
```
> **알림 읽기 API**
API : `api/v1/notification` [PUT]
해당 API를 사용하면 `isRead` 컬럼 값을 true로 반환할 수 있습니다.
- `isRead`: 사용자가 알람을 확인하였는지에 대한 구분 컬럼
- `isSent`: 서버에서 …
=> feat: add regist notification and read notification

src/main/java/com/twoclock/gitconnect/domain/like/dto/LikePopularWeekMemberRespDto.java, src/main/java/com/twoclock/gitconnect/domain/like/dto/LikePopularWeekRepositoryRespDto.java, src/main/java/com/twoclock/gitconnect/domain/like/entity/Likes.java, src/main/java/com/twoclock/gitconnect/domain/like/repository/CustomLikeRepository.java, src/main/java/com/twoclock/gitconnect/domain/like/repository/LikeRepository.java, src/main/java/com/twoclock/gitconnect/domain/like/repository/LikeRepositoryImpl.java, src/main/java/com/twoclock/gitconnect/domain/like/service/LikeService.java, src/main/java/com/twoclock/gitconnect/domain/like/web/LikeController.java, src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java, src/main/java/com/twoclock/gitconnect/global/dummy/DummyDevlnit.java, src/test/java/com/twoclock/gitconnect/domain/like/service/LikeServiceTest.java
* #114 
* 한 주 동안 인기 계정 및 저장소 기능을 구현 했습니다.
* 기능이 정상적으로 작동 하는지 안하는지 정도의 테스트 코드만 작성해둔 상태입니다.
> GET http://127.0.0.1:8082/api/v1/likes/popular-week/members
```json
{
"data": [
{
"login": "loginId-2",
"avatarUrl": "https://robohash.org/ocptvnbq.png"
},
{
"login": "loginId-1",
"avatarUrl": "https://robohash.org/luwvmskq.png"
}
]
}
```
> GET http://127.0.0.1:8082/api/v1/likes/popular-week/repositories
```json
{
"data": [
{
"boardId": 101,
"title": "저장소 홍보 테스트 게시글0",
"content": "테스트 게시글 내용0",
"login": "loginId-1",
"likeCount": 2
},
{
"boardId": 151,
"title": "저장소 홍보 테스트 게시글20",
"content": "테스트 게시글 내용0",
"login": "loginId-2",
"likeCount": 1
}
]
}
```
=> feat: Implement weekly popular members and repositories based on likes

src/main/java/com/twoclock/gitconnect/domain/chat/service/ChatMessageService.java, src/main/java/com/twoclock/gitconnect/domain/comment/service/CommentService.java, src/main/java/com/twoclock/gitconnect/domain/like/service/LikeService.java, src/main/java/com/twoclock/gitconnect/domain/notification/entity/Notification.java, src/main/java/com/twoclock/gitconnect/domain/notification/service/NotificationService.java, src/main/java/com/twoclock/gitconnect/domain/notification/web/NotificationController.java
* #118 
> 알림 삭제 기능 구현
`API : /api/v1/notification/{notificationId}`
- soft delete로 구현
> 추가적으로 기존 알림 저장 시 Notification Entity 에서 DB에 알림 보내는 사람을 저장하였습니다
> 이 부분 알림을 받는 사용자로 수정하였습니다.
=> feat: add soft delete to notification 

src/main/java/com/twoclock/gitconnect/global/config/WebSecurityConfig.java, src/main/java/com/twoclock/gitconnect/global/dummy/DummyObject.java, src/test/java/com/twoclock/gitconnect/config/IntegrationTestSupport.java, src/test/java/com/twoclock/gitconnect/domain/comment/service/CommentServiceTest.java
* #121 
> **댓글 관련 서비스 계층 테스트 코드 작성**
- service method를 대부분 `void` 형태로 처리하다 보니 값 검증에 대한 방법이 `verify` 말고는 딱히 생각나지 않네요
```
/** 테스트 목록*/
1. Comment 정상 입력 시 성공 
2. Comment 작성자와 Board 작성자가 동일 한 경우 알람 발송 X
3. Comment 작성자와 Board 작성자가 동일하지 않은 경우 알람 발송
4. Comment 내용에 비속어가 존재할 경우 에러 반환
5. 작성된 Board가 존재하지 않을 경우 등록 X
6. 잘못된 사용자 key 사용 경우 Comment 작성 불가
```
추가적으로 테스트 코드 처음 작성할 때 `통합 테스트` 도 고려하여  `IntegrationTestSupport` 라는 Class를 생성해 놓긴 했습니다.
근데 생각해보니 통합테스트까지 처리할 시간적 여유가 있을지 모르겠네요
추후 개발 상황 봐서 불필요하다 싶으면 삭제하겠습니다.
=> test: add Comment entity Business layer test code
